development:
  adapter: mysql2
  dataserver: localhost
  database: datacenter_dev
  username: root
  password: 
  
test:
  adapter: mysql2
  dataserver: localhost
  database: datacenter_test
  username: root
  password: 